# scp compose.yml sihuan@192.168.2.91:~/auth
# docker compose up -d --build
# docker run -d --name mycontainer -p 80:80 myimage
---
services:
  fiefclient:
    image: docker.io/library/fief-client:v1
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /share/infra/cert/docker:/etc/docker/certs.d
    ports:
      - 8001:80
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
