# scp compose.yml sihuan@192.168.2.91:~/auth
# docker compose up -d --build
# docker run -d --name mycontainer -p 80:80 myimage
---
services:
  fief-client:
    container_name: fief-client
    build:
      context: .
      args:
        - --no-cache
    volumes:
      - /share/infra/cert/docker:/etc/docker/certs.d
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
